ADDDED NEW QUESTION
alexakasanjeev/Interviewee-Questions pull request #15
Opened 2019-10-19 07:37 UTC by scamander27

2019-10-19 08:52 UTC, alexakasanjeev commented
hi @scamander27  Thank you so much for the your contribution 🎉

2019-10-22 18:40 UTC, rishabh115 commented
hi @scamander27 ,  this is quite an unhandy question to ask before accepting the job offer.

2019-10-23 16:13 UTC, sanjeevyadavIT requested changes
Hi @scamander27, We have requested some changes, please go through the review, and makes changes accordingly :hammer: 

We would be happy to merge your PR after the changes :rocket:

2019-10-23 16:13 UTC, alexakasanjeev commented on README.md
> +| 19 | Can I work from home on Fridays?|
This question, might not be good for first impression towards the interviewer, could you please change the question.

2019-11-04 18:39 UTC, alexakasanjeev commented
Hi @scamander27 there are some changes requested in the PR, if no activity is found within 7 days, this PR will be closed.

2019-11-13 17:47 UTC, closed without merging