Second Question added
alexakasanjeev/Interviewee-Questions pull request #3
Opened 2019-10-14 12:15 UTC by vb-vinay

One question is added and spelling of 'portrays' is corrected

2019-10-14 13:22 UTC, sanjeevyadavIT requested changes
Update the question number, and resolve the conflict

2019-10-14 13:22 UTC, alexakasanjeev commented on README.md
> +| 2 | Is it valid to change the probation period from 6 months (as mentioned by the HR on the Interview Day) to "12 months", in the offer letter which is received 1 month after the Interview and is j
Please change the correct question number

2019-10-19 18:45 UTC, vb-vinay commented
The question numbers have been changed and conflict is resolved

2019-10-25 06:51 UTC, rishabh115 approved these changes
Fixed the question number issue.

2019-10-25 06:51 UTC, merged